[package]
name = "weather-strategy"
version = "0.1.0"
edition = "2021"

[dependencies]
weather-config = { path = "../weather-config" }
weather-pricing = { path = "../weather-pricing" }
weather-types = { path = "../weather-types" }
chrono = { workspace = true }
rust_decimal = { workspace = true }
rust_decimal_macros = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
